[package]
name = "crate_example"
version = "0.1.0"
edition = "2024"

[dependencies]
# external_lib_example = {version = "1.0.0", features = ["feature_1", "feature_2"]}


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3 # higher = better optimization
